version: '3.3'

networks:
  net-db:
    driver: bridge
  net-app:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - net-db

  backend:
    container_name: nestjs-app
    image: nestjs-app
    build:
      context: ./Back
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3001:3001
      - 5555:5555
    networks:
      - net-db
      - net-app
    depends_on:
      - postgres
    volumes:
      - ./Back:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=zboub@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=0000
    ports:
      - "5050:80"
    networks:
      - net-db
    container_name: pgadmin
    depends_on:
      - postgres
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Front:/usr/src/app
      - /usr/src/app/node_modules
    networks:
       - net-app
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
       - backend

volumes:
    db-data:
